# SPDX-FileCopyrightText: 2024 Maximilian Albert <maximilian.albert@gmail.com>
#
# SPDX-License-Identifier: MPL-2.0

version = 1

[[annotations]]
path = [
    "devbox.json",
    "devbox.lock",
]
SPDX-FileCopyrightText = "2024 Maximilian Albert <maximilian.albert@gmail.com>"
SPDX-License-Identifier = "MPL-2.0"
